blog/urls.py
from django.urls import path
from . import views


app_name ='blog'

urlpatterns=[
path("",views.index,name='index'),
path("about/",views.about,name='about'),
path("twitter/",views.tweet,name='tweet'),
path("<int:blog_id>/",views.detail,name='detail'),
path("<int:blog_id>/comment/",views.comment,name='comment'),
path("<int:blog_id>/ack/",views.ack,name='ack'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/',include('blog.urls'))

]

blog/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.

class Blog(models.Model):
    blog_head = models.CharField(max_length=200)
    blog_content = models.CharField(max_length =1000)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.blog_head

class Comment(models.Model):
    comment_text = models.ForeignKey(Blog,on_delete= models.CASCADE)
    put_comment = models.CharField(max_length=200)
    co_date = models.DateTimeField('date published')
    def __str__(self):
        return self.put_comment
        '''
#<a href="{% url 'blog:comment' com.id %}">+Comment</a>
'''

blog/views.py
from django.http import HttpResponse
from .models import Blog,Comment
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
# Create your views here.
def index(request):
    blog_latest_list = Blog.objects.all()
    context={ "blog_latest_list" : blog_latest_list }
    return render(request,'blog/index.html',context)

def detail(request,blog_id):
    blogcontent = get_object_or_404(Blog, pk=blog_id)
    order=blogcontent.comment_set.order_by('-co_date')
    context={'blogcontent':blogcontent,"order":order}
    return render(request, 'blog/detail.html',context ) #change

def comment(request,blog_id):
    blo=Blog.objects.get(pk=blog_id)
    context ={"blog_id":blog_id,"blo":blo}
    return render(request, 'blog/comment.html',context)

def ack(request,blog_id):
    p = Blog.objects.get(pk=blog_id)
    p.comment_set.create(put_comment=request.POST['comment'],co_date=timezone.now())
    return render(request, 'blog/ack.html',{"p":p})

def tweet(request):
    return render(request,'blog/tweet.html')

def about(request):
    return render(request,'blog/about.html')

blog/templates/blog/about.html
<!DOCTYPE html>

{% extends 'blog/index.html' %}

{% block body_block %}
{% load static %}
<h1>about</h1>
<img src="{% static "blog/images/p.jpg"%}" alt="">


{% endblock %}

blog/templates/blog/ack.html
<!DOCTYPE html>
{% extends 'blog/index.html' %}

{% block body_block %}

<p>You commneted on <strong> {{p.blog_head}}</strong></p>


 {% endblock %}

blog/templates/blog/comment.html
<!DOCTYPE html>
{% extends 'blog/index.html' %}

{% block body_block %}

<h1>ADD YOUR COMMENT</h1>
<p>you are going to add comment on:{{blo.blog_head}}</p>

<form action="{% url 'blog:ack' blog_id %}" method="post">
{% csrf_token %}

<input type="text" name="comment" value="" placeholder="add comment here">

<input type="submit" value="Comment">
</form>


 {% endblock %}

blog/templates/blog/detail.html
<!DOCTYPE html>

{% extends 'blog/index.html' %}

{% block body_block %}
<h1>{{ blogcontent.blog_head }}</h1>
{{ blogcontent.blog_content }}

<h4 id='k'>published on:<p id='p'>{{blogcontent.pub_date}}</p></h4>

<h3>COMMENTS</h3>

{% for com in order %}
    <p id='k'><strong>{{com}}</strong>, commented on:{{com.co_date}}</p>
{% endfor%}
<a href="{% url 'blog:comment' blogcontent.id %}">Comment</a>


{% endblock %}

blog/templates/blog/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
<link rel="stylesheet" href="{% static "blog/css/style.css" %}">

    <title>Akhil</title>
  </head>
  <body>
<a href="{%url 'blog:index' %}">BLOG</a>
<a href="{%url 'blog:about' %}">ABOUT</a>
<a href="{%url 'blog:tweet' %}">TWEET</a>
<h1></h1>
    {% block body_block %}
      <h1 id="A">TECH WITH AKHIL</h1>
      <h1>WELCOME TO MY TECH BLOG</h1>
      <img src="{% static "blog/images/blog.jpg"%}" alt="">
      {% if blog_latest_list  %}
          <h2>BLOGS !!!</h2>
          <ul>
              {% for blog in blog_latest_list %}

                <li> <a href="{% url 'blog:detail' blog.id %} ">{{ blog.blog_head }} </a></li>
              {% endfor %}
          </ul>
          {% else %}
          <p>No blogs are available.</p>
      {% endif %}

    {% endblock %}

  </body>
</html>

blog/templates/blog/tweet.html
<!DOCTYPE html>
{% extends 'blog/index.html' %}

{% block body_block %}
{% load static %}
<h1>twitter</h1>
<img src="{% static "blog/images/t.jpg"%}" alt="">

 {% endblock %}